# Generated by Django 2.1 on 2018-10-16 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='lan_pics', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SyntaxPost', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
