# Generated by Django 2.1 on 2018-11-19 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_language_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntaxpost',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=3000, verbose_name='Contenido'),
        ),
    ]
