# Generated by Django 2.1.3 on 2018-12-01 20:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181119_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('mensaje', ckeditor.fields.RichTextField(max_length=3000, verbose_name='Tu mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langName', models.CharField(max_length=30, verbose_name='Nombre del Lenguaje')),
                ('langVer', models.CharField(max_length=30, verbose_name='Version del Lenguaje')),
                ('website', models.CharField(max_length=50, verbose_name='Página Oficial')),
                ('comments', ckeditor.fields.RichTextField(max_length=3000, verbose_name='Descripcion')),
            ],
        ),
    ]
